import axiosWithExtra from "../utils/axiosWithExtra";


const FETCHING_FRIENDS = "FETCHING_FRIENDS"
const FETCHING_FRIENDS_SUCCESS = "FETCHING_FRIENDS_SUCCESS"
const FETCHING_FRIENDS_FAILURE = "FETCHING_FRIENDS_FAILURE"

const ADDING_FRIEND = "ADDING_FRIEND"
const ADDING_FRIEND_SUCCESS = "ADDING_FRIEND_SUCCESS"
const ADDING_FRIEND_FAILURE = "ADDING_FRIEND_FAILURE"

const DELETING_FRIEND = "DELETING_FRIEND"
const DELETING_FRIEND_SUCCESS = "DELETING_FRIEND_SUCCESS"
const DELETING_FRIEND_FAILURE =  "DELETING_FRIEND_FAILURE"

const EDITING_FRIEND = "EDITING_FRIEND" 
const EDITING_FRIEND_SUCCESS = "EDITING_FRIEND_SUCCESS" 
const EDITING_FRIEND_FAILURE = "EDITING_FRIEND_FAILURE"

const fetchFriends = () => dispatch => {
    dispatch({
        type: FETCHING_FRIENDS
    })
}